#!/bin/bash
echo Running clean
./cleanup.sh >/dev/null
echo Committing the rest
svn add * */* */*/* */*/*/* */*/*/*/*
svn commit --message x
svn update
# svn revert * */* */*/* */*/*/* */*/*/*/*
#./remove-batchfiles.sh >/dev/null
exit 0

